-- Run this SQL directly in psql or Neon SQL editor to create admin account
-- Password will be hashed: admin123

INSERT INTO admins (email, password, created_at)
VALUES (
  'admin@college.edu',
  '$2a$10$rOzJ5XLPFqLgJjzW8X5H5uG2W8X5H5uG2W8X5H5uG2W8X5H5uG2W8X', -- This is a placeholder, will be properly hashed
  NOW()
)
ON CONFLICT (email) DO UPDATE
SET password = '$2a$10$rOzJ5XLPFqLgJjzW8X5H5uG2W8X5H5uG2W8X5H5uG2W8X5H5uG2W8X'; -- Placeholder

-- Better: Generate hash using this query after tables are created
-- The password 'admin123' hashed with bcrypt (10 rounds) would be generated by the app
-- For now, run the Node.js script when connection works, or use this to create tables first:

